// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uelpknvcdovlfnrvmszv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbHBrbnZjZG92bGZucnZtc3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTM3NzEsImV4cCI6MjA2OTQ2OTc3MX0.YzKi3uPUgojnNLyOFH9YmbFUWDaE-fhe0LY1itwWPGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});